name: PR checks
on:
  pull_request:
    branches:
      - main
      - '**'

jobs:
  test-add:
    strategy:
      fail-fast: false
      matrix:
        attempt_x: ['a', 'b', 'c', 'd', 'e', 'f']
        attempt_y: ['1', '2', '3', '4', '5', '6']
        attempt_z: ['i', 'ii', 'iii', 'iv', 'v', "vi"]
    runs-on: depot-ubuntu-22.04-16
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python
        with:
          python-version: 3.12
      - uses: ./.github/actions/tilt
      - name: Test
        run: bin/cluster-test.sh bash -c 'python -m pytest -s "chromadb/test/property/test_add.py"'
        shell: bash
        env:
          PROPERTY_TESTING_PRESET: normal
      - name: Get logs of all services
        id: get-logs
        if: failure()
        run: bin/get-logs.sh
        shell: bash
      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test_add_log_${{ matrix.attempt_x }}_${{ matrix.attempt_y }}_${{ matrix.attempt_z }}
          path: ~/work/chroma/chroma/**/*.log
  test-embeddings:
    strategy:
      fail-fast: false
      matrix:
        attempt_x: ['a', 'b', 'c', 'd', 'e', 'f']
        attempt_y: ['1', '2', '3', '4', '5', '6']
        attempt_z: ['i', 'ii', 'iii', 'iv', 'v', "vi"]
    runs-on: depot-ubuntu-22.04-16
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python
        with:
          python-version: 3.12
      - uses: ./.github/actions/tilt
      - name: Test
        run: bin/cluster-test.sh bash -c 'python -m pytest -s "chromadb/test/property/test_add.py"'
        shell: bash
        env:
          PROPERTY_TESTING_PRESET: normal
      - name: Get logs of all services
        id: get-logs
        if: failure()
        run: bin/get-logs.sh
        shell: bash
      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test_embeddings_log_${{ matrix.attempt_x }}_${{ matrix.attempt_y }}_${{ matrix.attempt_z }}
          path: ~/work/chroma/chroma/**/*.log
